### ISSUE TITLE
Implement Naive Baseline text processor

### ISSUE THREAD

**Issue by EhrenbruderRoschtbraten** [Ctrl-Alt-Defeat-Foundation-Models/informatiCup2024#20]

**Comment by LeviUniAcc** [comment]
is naive baseline text processor the same as in the example with " " -> "  " or what is it?

**Comment by EhrenbruderRoschtbraten** [comment]
> is naive baseline text processor the same as in the example with " " -> " " or what is it?

Yes, it only changes the scpaces for two spaces
